### ISSUE TITLE
Icon Modification

### ISSUE THREAD

**Issue by n-ce** [martinmimigames/little-music-player#19]
The Pixelated Icon is very distracting and does not fit in with the other os elements well, is this a functional choice to keep size low or is it of aesthetic value?

**Comment by wmartinmimi** [comment]
Short answer: 

Yes, but you're welcome to suggest change. :)

Long answer:

It is kind of neither, but both.

At first, the icon was just a quick sketch for testing at first, and the pixel art app is the closest thing at the time.

Later on, the app is developed for compatibility and size. And currently, it also needs to stand out from other music players, to gain user base. Strangely, the icon fits the specifications quite well. It is small, compatible, and unique.

It may be difficult to fit in with the different os, as compatibility is key in this app. Different android versions and manufacturers all have different styles and themes, so trying to fit in with them all can be difficult. Therefore it might be better to stand out instead, as it does not favour a system over the other.

However, as you said, this icon design can be distracting, and does not exist in harmony with other elements, and therefore can be an issue to look into.

Being a poor artist, I do not have the skills to solve this. However, I welcome any applicable and favoured changes.

~

Sorry for the long paragraph, but I guess it would be a good explanation as in why it is the icon.

**Comment by n-ce** [comment]
I looked into the icon. It is contrary to what i thought very tiny in size. As such I would highlight what was distracting was the red status bar icon. It should be the same color as other status bar icons.

**Comment by n-ce** [comment]
![maskable_icon_x128](https://user-images.githubusercontent.com/69345507/204079860-1ee59a29-00bc-4d09-9ef5-f8cd32337ca7.png)

I think Having a maskable icon like this helps.

**Comment by wmartinmimi** [comment]
Potentially. I'll see if the code for masking would be bigger than or smaller than just using an alternative image.

If it is bigger, would you consider this icon? ![2022-11-26_08.52.00.png](https://user-images.githubusercontent.com/82596011/204080776-745ceaa8-8c4d-42bb-ad3d-2387d042e949.png)

It is smaller than the old icon, and wouldn't affect the looks too much.

I think your solutions will probably work better tho.

**Comment by n-ce** [comment]
> I'll see if the code for masking would be bigger than or smaller than just using an alternative image.
I was wondering this too
So we have two cases 
1. Have two icons
  - one old icon and
  - one new icon for status bar
2. Have one icon
  - changing the color to white for status bar
  - turning it into maskable

**Comment by josephg5** [comment]
svg?

**Comment by wmartinmimi** [comment]
I don't think android supports svg for icons, or at least not for older androids.

I believe Android 5.0 or below do not support Vector Drawables natively, and I plan to support Android 1.0+ with as little code as possible.

Nice idea though, I wish they supported svg before.

**Comment by wmartinmimi** [comment]
New icon in [this release](https://github.com/martinmimigames/little-music-player/releases/tag/2.8).
The status bar icon should now be white/dark.
I went with the 2 icon route btw.

**Comment by n-ce** [comment]
great work, would you explain the icon design change though? I dont notice any massive changes in the size and from my pov, the previous icon felt kind of iconic and with due respect the current one is kind of dull.

**Comment by wmartinmimi** [comment]
So, should I use the old version of the icon (ie. the orange one with transparent background) and an extra white only version of that for the notification?

I have to agree, it is not as iconic as before.

**Comment by wmartinmimi** [comment]
Changed it back now. [New release](https://github.com/martinmimigames/little-music-player/releases/tag/2.9)

**Comment by n-ce** [comment]
This will do, best of both worlds. Closing this now. :)
