### ISSUE TITLE
Removing internal app Interface to reduce app size

### ISSUE THREAD

**Issue by n-ce** [martinmimigames/little-music-player#20]
My proposal is to remove the app interface in favor of clicking on app icon directly and take user to file manager to choose audio.
What do you think?

**Comment by wmartinmimi** [comment]
Smart idea!

I might split this project into 2 projects.
One for a more fuller app (with folder selection), and one for basic audio playing (no need for ui).

**Comment by n-ce** [comment]
You stole my words! Thats exactly what i was thinking of. That variation could also commit to #18 and other basic features.

**Comment by wmartinmimi** [comment]
Done with [Tiny Music Player](https://github.com/martinmimigames/tiny-music-player).
However f-droid inclusion may take a while.
